=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/dtd/sql-info.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT sqlinfos (sqlinfo*)>
<!ELEMENT sqlinfo (sqlname,sql+,checks*,querytree?)>
<!ATTLIST sqlinfo sqlid ID #REQUIRED>
<!ELEMENT sqlname (#PCDATA)>
<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql dialect (oracle|db2|all) "all">

<!ELEMENT checks (check+)>
<!ELEMENT check (checkname,(checksql+|checkexeid|checkstring),compareval,errtext)>
<!ATTLIST check comparesign (eql|uneql|gt|gteql|lt|lteql) "eql"
                exitall (true|false) "true">
<!ELEMENT checkname (#PCDATA)>
<!ELEMENT checksql (#PCDATA)>
<!ATTLIST checksql dialect (oracle|mysql|db2|all) "all">
<!ELEMENT checkexeid (#PCDATA)>
<!ELEMENT checkstring (#PCDATA)>
<!ELEMENT compareval (#PCDATA)>
<!ELEMENT errtext (#PCDATA)>

<!ELEMENT querytree EMPTY>
<!ATTLIST querytree idcolumn CDATA #REQUIRED
                    textcolumn CDATA #REQUIRED
                    iconClscolumn CDATA #IMPLIED
                    iconcolumn CDATA #IMPLIED
                    diffway (upper|pos) "upper"
                    diffcondition CDATA #REQUIRED
                    initexpand (one|all|none) "none"
                    isasync (true|false) "false">

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY008/sql-JY0008-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>
	<sqlinfo sqlid="JY8001Q001">
		<sqlname>查询仓库物资入库数量信息</sqlname>
		<sql><![CDATA[
			SELECT
			    p1.param_name putin_storehouse_name,
				t1.jy_material_id,
				sum(t1.putin_number) putin_number,
				t2.`code` material_code,
				t2.`name` material_name,
				t2.model,
				t2.supplier,
				t3.`code` material_type_code,
				t3.`name` material_type_name
			FROM
				jy_storehouse_in t0
			LEFT JOIN jy_storehouse_in_detail t1 ON t0.id = t1.jy_storehouse_in_id
			LEFT JOIN jy_material t2 ON t1.jy_material_id = t2.id
			LEFT JOIN jy_material_type t3 ON t2.jy_material_type_id = t3.id
			LEFT JOIN jy_params p1 ON t0.putin_storehouse_code = p1.param_code
			WHERE
				t0.putin_storehouse_code = $S{storehouse_code}
			AND
				(
	                $ISNULL{material_id}
	                OR t1.jy_material_id = $N{material_id}
	            )
	        AND t0.`status` = 2
			ORDER BY
				t1.jy_material_id;
		]]></sql>
	</sqlinfo>
	

	<sqlinfo sqlid="JY8001Q002">
		<sqlname>查询仓库物资出库数量信息</sqlname>
		<sql><![CDATA[
			SELECT
				t1.jy_material_id,
				sum(t1.putout_number) putout_number
			FROM
				jy_storehouse_out t0
			LEFT JOIN jy_storehouse_out_detail t1 ON t0.id = t1.jy_storehouse_out_id
			WHERE
				t0.putin_storehouse_code = $S{storehouse_code}
			AND
				(
	                $ISNULL{material_id}
	                OR t1.jy_material_id = $N{material_id}
	            )
	        AND t0.`status` = 2
			ORDER BY
				t1.jy_material_id;
		]]></sql>
	</sqlinfo>


	<sqlinfo sqlid="JY8001Q003">
		<sqlname>查询物资仓储预警信息</sqlname>
		<sql><![CDATA[
			SELECT
				t1.id,
				t1.warn_storehouse_code,
				p1.param_name warn_storehouse_name,
				t1.jy_material_id,
				t1.warn_number,
				t1.inputuser,
				t1.remark,
				t1.crt_date,
				t2.`code` material_code,
				t2.`name` material_name,
				t2.model,
				t2.supplier,
				t3.`code` material_type_code,
				t3.`name` material_type_name
			FROM
				jy_material_warn t1
			LEFT JOIN jy_material t2 ON t1.jy_material_id = t2.id
			LEFT JOIN jy_material_type t3 ON t2.jy_material_type_id = t3.id
			LEFT JOIN jy_params p1 ON t1.warn_storehouse_code = p1.param_code
			WHERE
			(
				t1.inputuser = $N{sys_user_id} 
			)
			AND
			(
                $ISNULL{id}
                OR t1.id = $N{id}
            )
            AND
			(
                $ISNULL{warn_storehouse_code}
                OR t1.warn_storehouse_code = $S{warn_storehouse_code}
            )
            AND
			(
                $ISNULL{jy_material_id}
                OR t1.jy_material_id = $N{jy_material_id}
            )
			
		]]></sql>
	</sqlinfo>


	<sqlinfo sqlid="JY8001U001">
		<sqlname>新增物资仓储预警信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_material_warn (
			    jy_material_id,
			    warn_storehouse_code,
			    warn_number,
				remark,
				inputuser,
				crt_date,
				crt_time
			)
			VALUES
			(
				$S{jy_material_id},
				$S{warn_storehouse_code},
				$N{warn_number},
				$S{remark},
				$N{sys_user_id},
				$S{SYSDATE},
				$S{SYSTIME}
			);
		]]></sql>
	</sqlinfo>


	<sqlinfo sqlid="JY8001D001">
		<sqlname>删除物资仓储预警信息</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_material_warn where id = $N{id}
		]]></sql>
	</sqlinfo>
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY004/sql-JY0004-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>

	<sqlinfo sqlid="JY4001Q001">
		<sqlname>查询物资出库信息主表id，通过出库单号</sqlname>
		<sql><![CDATA[
		SELECT
				id
			FROM
				jy_storehouse_out
			WHERE
				putout_code =$S{putout_code};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY4001U001">
		<sqlname>生成出库单主表</sqlname>
		<sql><![CDATA[
		INSERT INTO jy_storehouse_out (
			putout_code,
			putout_type,
			putout_user,
			putout_date,
			putout_storehouse_code,
			apply_user,
			putin_storehouse_code,
			status,
			remark,
			inputuser,
			crt_date,
			crt_time
		) VALUES
		(
			$S{putout_code},
			$N{putout_type},
			$N{putout_user},
			$S{SYSDATE},
			$S{putout_storehouse_code},
			$N{apply_user},
			$S{putin_storehouse_code},
			$N{status},
			$S{remark},
			$N{sys_user_id},
			$S{SYSDATE},
			$S{SYSTIME}
		);
		
		]]></sql>
	</sqlinfo>
	
	
	
	<sqlinfo sqlid="JY4001U002">
		<sqlname>生成出库单明细表</sqlname>
		<sql><![CDATA[
		INSERT INTO jy_storehouse_out_detail (
			jy_storehouse_out_id,
			jy_material_id,
			putout_number
		) VALUES
		(
			$N{jy_storehouse_out_id},
			$N{jy_material_id},
			$N{putout_number}
		);
		]]></sql>
	</sqlinfo>
	
	
	
	
	
	
	
	

	
	
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY001/sql-JY0001-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>

	<sqlinfo sqlid="JY0001U001">
		<sqlname>新增物资类型</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_material_type (
				code,
				name
			)
			VALUES
				(
					$S{code},
					$S{name}
				)
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY0001Q001">
		<sqlname>查询全部物资类型</sqlname>
		<sql><![CDATA[
			SELECT * FROM jy_material_type
				WHERE 
				
				(
                $ISNULL{code}
                OR jy_material_type.CODE like '%$U{code}%'
            ) or (
            	$ISNULL{name}
                OR jy_material_type.name like '%$U{name}%'
            )
					order by jy_material_type.id
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY0001Q002">
		<sqlname>查询全部物资类型数量</sqlname>
		<sql><![CDATA[
			SELECT COUNT(a.id) num FROM jy_material_type a
				WHERE 
					(
                $ISNULL{code}
                OR jy_material_type.CODE like '%$U{code}%'
            ) or (
            	$ISNULL{name}
                OR jy_material_type.name like '%$U{name}%'
            )
		]]></sql>
	</sqlinfo>

</sqlinfos>
