=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/dtd/sql-info.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT sqlinfos (sqlinfo*)>
<!ELEMENT sqlinfo (sqlname,sql+,checks*,querytree?)>
<!ATTLIST sqlinfo sqlid ID #REQUIRED>
<!ELEMENT sqlname (#PCDATA)>
<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql dialect (oracle|db2|all) "all">

<!ELEMENT checks (check+)>
<!ELEMENT check (checkname,(checksql+|checkexeid|checkstring),compareval,errtext)>
<!ATTLIST check comparesign (eql|uneql|gt|gteql|lt|lteql) "eql"
                exitall (true|false) "true">
<!ELEMENT checkname (#PCDATA)>
<!ELEMENT checksql (#PCDATA)>
<!ATTLIST checksql dialect (oracle|mysql|db2|all) "all">
<!ELEMENT checkexeid (#PCDATA)>
<!ELEMENT checkstring (#PCDATA)>
<!ELEMENT compareval (#PCDATA)>
<!ELEMENT errtext (#PCDATA)>

<!ELEMENT querytree EMPTY>
<!ATTLIST querytree idcolumn CDATA #REQUIRED
                    textcolumn CDATA #REQUIRED
                    iconClscolumn CDATA #IMPLIED
                    iconcolumn CDATA #IMPLIED
                    diffway (upper|pos) "upper"
                    diffcondition CDATA #REQUIRED
                    initexpand (one|all|none) "none"
                    isasync (true|false) "false">

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY002/sql-JY0002-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>

	<sqlinfo sqlid="JY2001U001">
		<sqlname>新增入库基本信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_storehouse_in (
				putin_type,
				putin_user,
				putin_date,
				putin_storehouse_code,
				contract_no,
				STATUS,
				remark,
				inputuser,
				crt_date,
				crt_time
			)
			VALUES
			(
				$N{putin_type},
				$N{putin_user},
				$S{putin_date},
				$S{putin_storehouse_code},
				$S{contract_no},
				$N{status},
				$S{remark},
				$S{inputuser},
				$S{crt_date},
				$S{crt_time}
			)
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001U002">
		<sqlname>新增入库明细</sqlname>
		<sql><![CDATA[
		INSERT INTO jy_storehouse_in_detail (
			jy_storehouse_in_id,
			jy_material_id,
			putin_number
		)
		VALUES
		(
			$N{jy_storehouse_in_id},
			$N{jy_material_id},
			$N{putin_number}
		)
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001Q001">
		<sqlname>查询新增入库基本信息的id</sqlname>
		<sql><![CDATA[
		SELECT
				id
			FROM
				jy_storehouse_in
			WHERE
				crt_date =$S{crt_date}
				and
				crt_time =$S{crt_time}
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001Q002">
		<sqlname>查询物资已经对应的物资id</sqlname>
		<sql><![CDATA[
			SELECT
				id 'key',
				name 'value'
			FROM
				jy_material
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001Q003">
		<sqlname>查询所有入库记录</sqlname>
		<sql><![CDATA[
			SELECT * FROM jy_storehouse_in a
				WHERE 
					(
                $ISNULL{contract_no}
                OR a.contract_no like '%$U{contract_no}%'
            ) 
     			or
            (
               (
               $ISNULL{putin_date_start}
               or 
               a.putin_date > $S{putin_date_start}
               )
               or
               (
                $ISNULL{putin_date_end}
                or
                a.putin_date < $S{putin_date_end}
                )
            )
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001Q004">
		<sqlname>查询所有入库记录的数量</sqlname>
		<sql><![CDATA[
			SELECT COUNT(a.id) num FROM jy_storehouse_in a
				WHERE 
					(
                $ISNULL{contract_no}
                OR a.contract_no like '%$U{contract_no}%'
            ) 
            or
            (
               (
               $ISNULL{putin_date_start}
               or 
               a.putin_date > $S{putin_date_start}
               )
               or
               (
                $ISNULL{putin_date_end}
                or
                a.putin_date < $S{putin_date_end}
                )
            )
      
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001Q005">
		<sqlname>获取入库单对应的入库明细</sqlname>
		<sql><![CDATA[
			SELECT
				*
			FROM
				jy_storehouse_in_detail
			WHERE
				jy_storehouse_in_id = $N{id};
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001D001">
		<sqlname>删除入库单</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_storehouse_in where id = $N{id}
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001D002">
		<sqlname>删除入库单详细信息</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_storehouse_in_detail where jy_storehouse_in_id = $N{id}
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY2001U003">
		<sqlname>修改入库单信息</sqlname>
		<sql><![CDATA[
		UPDATE jy_storehouse_in SET
			putin_user=$N{putin_user},
			putin_date=$S{putin_date},
			putin_storehouse_code=$S{putin_storehouse_code},
			contract_no=$S{contract_no},
			remark=$S{remark},
			inputuser=$S{inputuser}
			WHERE id=$N{id}
		]]></sql>
	</sqlinfo>
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY005/sql-JY0005-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>
	<sqlinfo sqlid="JY5001U001">
		<sqlname>新增物资使用信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_material_use (
			    jy_material_id,
				use_user,
				use_date,
				use_number,
				status,
				remark,
				inputuser,
				crt_date,
				crt_time
			)
			VALUES
			(
				$N{jy_material_id},
				$N{sys_user_id},
				$S{use_date},
				$N{use_number},
				1,
				$S{remark},
				$N{sys_user_id},
				$S{SYSDATE},
				$S{SYSTIME}
			);
		]]></sql>
	</sqlinfo>
	


	<sqlinfo sqlid="JY5001Q001">
		<sqlname>查询当前用户物资使用信息</sqlname>
		<sql><![CDATA[
		SELECT
			t1.id,
			t1.jy_material_id,
			m1.`code` material_code,
			m1.`name` material_name,
			m1.model,
			m1.supplier,
			t1.use_user,
			u1.`name` user_name,
			t1.use_date,
			t1.use_number,
			t1.remark,
			t1.`status`
		FROM
			jy_material_use t1
		LEFT JOIN jy_user u1 ON t1.use_user = u1.id
		LEFT JOIN jy_material m1 ON t1.jy_material_id = m1.id
		WHERE
			(
				t1.use_user = $N{sys_user_id}
			)
			AND
			(
                $ISNULL{id}
                OR t1.id = $N{id}
            ) 
			AND
			(
                $ISNULL{jy_material_id}
                OR t1.jy_material_id = $N{jy_material_id}
            ) 
            AND
			(
                $ISNULL{status}
                OR t1.status = $N{status}
            ) 
            AND
			(
               $ISNULL{date_start}
               or 
               t1.use_date >= $S{date_start}
            )
             AND
            (
                $ISNULL{date_end}
                or
                t1.use_date <= $S{date_end}
            )
             
		]]></sql>
	</sqlinfo>


	<sqlinfo sqlid="JY5001Q002">
		<sqlname>查询当前用户物资使用信息</sqlname>
		<sql><![CDATA[
		SELECT
			t1.id,
			t1.jy_material_id,
			m1.`code` material_code,
			m1.`name` material_name,
			m1.model,
			m1.supplier,
			t1.use_user,
			u1.`name` user_name,
			t1.use_date,
			t1.use_number,
			t1.remark,
			t1.`status`
		FROM
			jy_material_use t1
		LEFT JOIN jy_user u1 ON t1.use_user = u1.id
		LEFT JOIN jy_material m1 ON t1.jy_material_id = m1.id
		WHERE
			
			(
                $ISNULL{id}
                OR t1.id = $N{id}
            ) 
			AND
			(
                $ISNULL{jy_material_id}
                OR t1.jy_material_id = $N{jy_material_id}
            ) 
            AND
			(
                $ISNULL{status}
                OR t1.status = $N{status}
            ) 
            AND
			(
               $ISNULL{date_start}
               or 
               t1.use_date >= $S{date_start}
            )
             AND
            (
                $ISNULL{date_end}
                or
                t1.use_date <= $S{date_end}
            )
            AND
            (
				$ISNULL{use_user_name}
                OR u1.`name` like '%$U{use_user_name}%'
			)
			
             
		]]></sql>
	</sqlinfo>

	<sqlinfo sqlid="JY5001Q003">
		<sqlname>查询当前用户物资持有信息（申请物资数量）</sqlname>
		<sql><![CDATA[
			SELECT
				t1.jy_material_id,
				sum(t1.apply_number) apply_number,
				t2.`code` material_code,
				t2.`name` material_name,
				t2.model,
				t2.supplier,
				t3.`code` material_type_code,
				t3.`name` material_type_name
			FROM
				jy_apply t0
			LEFT JOIN jy_apply_detail t1 ON t0.id = t1.jy_apply_id
			LEFT JOIN jy_material t2 ON t1.jy_material_id = t2.id
			LEFT JOIN jy_material_type t3 ON t2.jy_material_type_id = t3.id
			WHERE
				t0.`status` = 4
				and
				(
	                t0.apply_user = $N{sys_user_id}
	            ) 
	             AND
				(
	                $ISNULL{jy_material_id}
	                OR t1.jy_material_id = $N{jy_material_id}
	            ) 
	     			
			GROUP BY
				t1.jy_material_id
			
        ]]></sql>
	</sqlinfo>
	
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY006/sql-JY0006-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>
	<sqlinfo sqlid="JY6001U001">
		<sqlname>新增物资退回主表信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_storehouse_in (
			    putin_code,
			    putin_type,
				putin_user,
				putin_date,
				putin_storehouse_code,
				cancel_user,
				status,
				remark,
				inputuser,
				crt_date,
				crt_time
			)
			VALUES
			(
				$S{putin_code},
				$S{putin_type},
				$N{putin_user},
				$S{putin_date},
				$S{putin_storehouse_code},
				$N{sys_user_id},
				$N{status},
				$S{remark},
				$N{sys_user_id},
				$S{SYSDATE},
				$S{SYSTIME}
			);
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY6001U002">
		<sqlname>新增物资退回明细信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_storehouse_in_detail (
			jy_storehouse_in_id,
			jy_material_id,
			putin_number
		)
		VALUES
		(
			$N{jy_storehouse_in_id},
			$N{jy_material_id},
			$N{putin_number}
		);
		]]></sql>
	</sqlinfo>
	
	  
	<sqlinfo sqlid="JY6001U003">
		<sqlname>修改物资退回信息</sqlname>
		<sql><![CDATA[
			UPDATE jy_storehouse_in
			SET 
			putin_user = $N{putin_user}, 
			putin_date = $S{putin_date}, 
			putin_storehouse_code = $S{putin_storehouse_code}, 
			remark = $S{remark}
			WHERE
				id = $N{id};
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY6001U004">
		<sqlname>确认入库</sqlname>
		<sql><![CDATA[
		UPDATE jy_storehouse_in SET
			status=2
			WHERE id=$N{id}
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY6001Q001">
		<sqlname>查询新增物资退回信息的id</sqlname>
		<sql><![CDATA[
		SELECT
				id
			FROM
				jy_storehouse_in
			WHERE
				putin_code =$S{putin_code};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY6001Q002">
		<sqlname>查询当前用户的物资退回信息</sqlname>
		<sql><![CDATA[
			SELECT
				t0.id,
				t0.putin_type,
				t0.putin_code,
				t0.putin_user,
				u1.`name` putin_user_name,
				t0.putin_date,
				t0.putin_storehouse_code,
				p1.param_name putin_storehouse_name,
				t0.contract_no,
				t0.cancel_user,
				u2.`name` cancel_user_name,
				t0.putout_storehouse_code,
				p2.param_name putout_storehouse_name,
				t0.`status`,
			    t0.remark
			FROM
				jy_storehouse_in t0
			LEFT JOIN jy_user u1 ON t0.putin_user = u1.id
			LEFT JOIN jy_user u2 ON t0.cancel_user = u2.id
			LEFT JOIN jy_params p1 ON t0.putin_storehouse_code = p1.param_code
			LEFT JOIN jy_params p2 ON t0.putout_storehouse_code = p2.param_code
				WHERE 
				(
	                $ISNULL{id}
	                OR t0.id = $N{id}
	            ) 
	     			and
				(
	                $ISNULL{putin_type}
	                OR t0.putin_type = $N{putin_type}
	            ) 
	     			and
					(
	                $ISNULL{putin_user}
	                OR t0.putin_user = $N{putin_user}
	            ) 
	     			and
						(
	                $ISNULL{putin_code}
	                OR t0.putin_code like '%$U{putin_code}%'
	            ) 
     			and
            	(
               		$ISNULL{date_start}
               		or 
               		t0.putin_date >= $S{date_start}
               	)
               	and
               	(
                	$ISNULL{date_end}
                	or
                	t0.putin_date <= $S{date_end}
                )
	            
        ]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY6001Q003">
		<sqlname>查询物资退回明细信息通过主表id</sqlname>
		<sql><![CDATA[
			SELECT
				t2.id jy_material_id,
				t2.`code` code,
				t2.`name` name,
				t2.model,
				t2.supplier,
				t3.`code` material_type_code,
				t3.`name` codename,
				t1.putin_number
			FROM
				jy_storehouse_in_detail t1
			LEFT JOIN jy_material t2 ON t1.jy_material_id = t2.id
			LEFT JOIN jy_material_type t3 ON t2.jy_material_type_id = t3.id
			WHERE
				t2.id IS NOT NULL
			AND t1.jy_storehouse_in_id = $U{id}
		]]>
		</sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY6001Q004">
		<sqlname>查询物资退回状态通过主表id</sqlname>
		<sql><![CDATA[
		   SELECT
				status
			FROM
				jy_storehouse_in
			WHERE
				id =$N{id};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY6001D001">
		<sqlname>删除入库单</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_storehouse_in where id = $N{id}
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="JY6001D002">
		<sqlname>删除入库单详细信息</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_storehouse_in_detail where jy_storehouse_in_id = $N{id}
		]]></sql>
	</sqlinfo>
	
	
	
	
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY007/sql-JY0007-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>
	<sqlinfo sqlid="JY7001U001">
		<sqlname>新增物资仓储调拨信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_transfer (
			    transfer_code,
			    transfer_date,
			    transfer_type,
				putin_user,
				putin_storehouse_code,
				putout_user,
				putout_storehouse_code,
				status,
				remark,
				inputuser,
				crt_date,
				crt_time
			)
			VALUES
			(
				$S{transfer_code},
				$S{transfer_date},
				$N{transfer_type},
				$N{putin_user},
				$S{putin_storehouse_code},
				$N{putout_user},
				$S{putout_storehouse_code},
				1,
				$S{remark},
				$N{sys_user_id},
				$S{SYSDATE},
				$S{SYSTIME}
			);
		]]></sql>
	</sqlinfo>
	


	<sqlinfo sqlid="JY7001U002">
		<sqlname>新增物资仓储调拨信息明细</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_transfer_detail (
			jy_transfer_id,
			jy_material_id,
			transfer_number
		)
		VALUES
		(
			$N{jy_transfer_id},
			$N{jy_material_id},
			$N{transfer_number}
		);
		]]></sql>
	</sqlinfo>

				
   <sqlinfo sqlid="JY7001U003">
		<sqlname>修改物资仓储调拨信息明细</sqlname>
		<sql><![CDATA[
			UPDATE jy_transfer
			SET 
			transfer_date = $S{transfer_date}, 
			transfer_type = $N{transfer_type}, 
			putin_user = $N{putin_user}, 
			putin_storehouse_code = $S{putin_storehouse_code}, 
			putout_user = $N{putout_user}, 
			putout_storehouse_code = $S{putout_storehouse_code}, 
			remark = $S{remark},
			status = 1
			WHERE
				id = $N{id};
		]]></sql>
	</sqlinfo>


	<sqlinfo sqlid="JY7001U004">
			<sqlname>修改物资仓储调拨状态信息</sqlname>
			<sql><![CDATA[
			UPDATE jy_transfer
			SET 
			status = $N{status}
			WHERE
				id = $N{id};
			]]></sql>
	</sqlinfo>


    <sqlinfo sqlid="JY7001Q001">
		<sqlname>查询物资仓储调拨基本信息的id</sqlname>
		<sql><![CDATA[
		SELECT
				id
			FROM
				jy_transfer
			WHERE
				transfer_code =$S{transfer_code};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY7001Q002">
		<sqlname>查询物资仓储调拨基本信息</sqlname>
		<sql><![CDATA[
			SELECT
				t1.id,
				t1.transfer_code,
				t1.transfer_date,
				t1.transfer_type,
				t1.putin_user,
				u1.`name` putin_user_name,
				t1.putin_storehouse_code,
				p1.param_name putin_storehouse_name,
				t1.putout_user,
				u2.`name` putout_user_name,
				t1.putout_storehouse_code,
				p2.param_name putout_storehouse_name,
				t1.`status`,
				t1.remark,
				t1.inputuser,
				t1.crt_date,
				t1.crt_time
			FROM
				jy_transfer t1
			LEFT JOIN jy_user u1 ON t1.putin_user = u1.id
			LEFT JOIN jy_user u2 ON t1.putout_user = u2.id
			LEFT JOIN jy_params p1 ON t1.putin_storehouse_code = p1.param_code
			LEFT JOIN jy_params p2 ON t1.putout_storehouse_code = p2.param_code
			WHERE
			(
				t1.putin_user = $N{sys_user_id} or
				t1.putout_user = $N{sys_user_id} 
			)
			AND
			(
                $ISNULL{id}
                OR t1.id = $N{id}
            ) 
            AND
			(
                $ISNULL{transfer_type}
                OR t1.transfer_type = $N{transfer_type}
            )
			AND
			(
                $ISNULL{transfer_code}
                OR t1.transfer_code like '%$U{transfer_code}%'
            ) 
            AND
			(
                $ISNULL{date_start}
                OR t1.transfer_date >= $S{date_start}
            ) 
            AND
			(
                $ISNULL{date_end}
                OR t1.transfer_date <= $S{date_end}
            ) 
            AND
			(
                $ISNULL{putin_user}
                OR t1.putin_user = $S{putin_user}
            )
            AND
			(
                $ISNULL{putin_storehouse_code}
                OR t1.putin_storehouse_code = $S{putin_storehouse_code}
            ) 
             AND
			(
                $ISNULL{putout_user}
                OR t1.putout_user = $S{putout_user}
            )
            AND
			(
                $ISNULL{putout_storehouse_code}
                OR t1.putout_storehouse_code = $S{putout_storehouse_code}
            ) 
			
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY7001Q003">
		<sqlname>查询物资仓储调拨明细信息通过主表id</sqlname>
		<sql><![CDATA[
			SELECT
				t1.jy_transfer_id,
				t1.jy_material_id,
				t1.transfer_number,
				t2.`code` material_code,
				t2.`name` material_name,
				t2.model,
				t2.supplier,
				t3.`code` material_type_code,
				t3.`name` material_type_name
			FROM
				jy_transfer_detail t1
			LEFT JOIN jy_material t2 ON t1.jy_material_id = t2.id
			LEFT JOIN jy_material_type t3 ON t2.jy_material_type_id = t3.id
			WHERE
				jy_transfer_id = $N{id};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY7001Q004">
		<sqlname>查询物资仓储调拨明细的状态</sqlname>
		<sql><![CDATA[
			SELECT
				t1.`status`
			FROM
				jy_transfer t1
			WHERE
				t1.id =$S{id};
		]]></sql>
	</sqlinfo>
	
	
	
	<sqlinfo sqlid="JY7001D001">
		<sqlname>删除物资仓储调拨主表</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_transfer where id = $N{id}
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY7001D002">
		<sqlname>删除物资仓储调拨明细</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_transfer_detail where jy_transfer_id = $N{id}
		]]></sql>
	</sqlinfo>
	
	
	
	
	
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/SYS/sql-sys-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">
<!-- 平台系统功能的SQL在这里配置 -->
<sqlinfos>

	<sqlinfo sqlid="SYS_QRY_PARAM">
		<sqlname>查询系统参数信息</sqlname>
		<sql><![CDATA[
		SELECT paraid,paravalue,groupparaid,paraname FROM sys_param 
				  ORDER BY groupparaid,paraid
		]]></sql>
	</sqlinfo>

	<sqlinfo sqlid="SYS_QRY_DICT">
		<sqlname>查询数据字典数据</sqlname>
		<sql><![CDATA[
		SELECT itemKey,itemVal FROM sys_dict_item WHERE dict=$S{dict} ORDER BY itemKey
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="SYS100000">
		<sqlname>查询系统菜单（所有）</sqlname>
		<sql><![CDATA[
		SELECT menuid,menuname,upperid,url,iconcls,icon,status,moduleid,pageid,fastcode,functype,menutype 
		FROM sys_menu 
		WHERE status='N' 
		ORDER BY upperid,loadorder,menuid  
		]]></sql>
		<querytree idcolumn="menuid" textcolumn="menuname"
			iconClscolumn="iconcls" iconcolumn="icon" diffcondition="menuid,upperid" initexpand="all" />
	</sqlinfo>

	<sqlinfo sqlid="SYSWORKDAYQ">
		<sqlname>查询系统工作日</sqlname>
		<sql dialect="oracle"><![CDATA[
			SELECT workday FROM sys_workday_set 
			WHERE pgmno in (select p.pgmno from sys_workday_pgm p where p.pgmtype = '1')
			  AND to_date(workday,'yyyymmdd') between (to_date($s{sys_param_50000002},'yyyymmdd') - 360) and (to_date($s{sys_param_50000002},'yyyymmdd') + 360) 
			ORDER BY workday
		]]></sql>
		<sql dialect="db2"><![CDATA[
			SELECT workday FROM sys_workday_set 
			WHERE pgmno in (select p.pgmno from sys_workday_pgm p where p.pgmtype = '1')
			  AND days(to_date(workday,'yyyymmdd')) between (days(to_date($s{sys_param_50000002},'yyyymmdd')) - 360) and (days(to_date($s{sys_param_50000002},'yyyymmdd')) + 360) 
			ORDER BY workday
		]]></sql>
	</sqlinfo>

</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/JY003/sql-JY0003-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../dtd/sql-info.dtd">

<sqlinfos>

	<sqlinfo sqlid="JY3001U001">
		<sqlname>新增申请基本信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_apply (
			    apply_code,
				apply_user,
				apply_date,
				review_user,
				storehouse_user,
				apply_storehouse_code,
				status,
				remark,
				inputuser,
				crt_date,
				crt_time
			)
			VALUES
			(
				$S{apply_code},
				$N{sys_user_id},
				$S{apply_date},
				$N{review_user},
				$N{storehouse_user},
				$S{apply_storehouse_code},
				$N{status},
				$S{remark},
				$N{sys_user_id},
				$S{SYSDATE},
				$S{SYSTIME}
			);
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY3001U002">
		<sqlname>新增申请基本信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_apply_detail (
			jy_apply_id,
			jy_material_id,
			apply_number
		)
		VALUES
		(
			$N{jy_apply_id},
			$N{jy_material_id},
			$N{apply_number}
		);
		]]></sql>
	</sqlinfo>
	
	
	
	<sqlinfo sqlid="JY3001U003">
		<sqlname>修改申请单信息</sqlname>
		<sql><![CDATA[
		UPDATE jy_apply
		SET 
		apply_date = $S{apply_date}, 
		review_user = $N{review_user}, 
		storehouse_user = $N{storehouse_user}, 
		apply_storehouse_code = $S{apply_storehouse_code}, 
		remark = $S{remark}
		WHERE
			id = $N{id};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY3001U004">
		<sqlname>领导审核修改申请单信息</sqlname>
		<sql><![CDATA[
		UPDATE jy_apply
		SET 
		status = $N{status}, 
		review_date = $S{review_date}, 
		review_remark = $S{review_remark}
		WHERE
			id = $N{id};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY3001Q001">
		<sqlname>查询新增申请基本信息的id</sqlname>
		<sql><![CDATA[
		SELECT
				id
			FROM
				jy_apply
			WHERE
				apply_code =$S{apply_code};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY3001Q002">
		<sqlname>查询当前用户的申请信息</sqlname>
		<sql><![CDATA[
		SELECT
			t1.id,
			t1.apply_code,
			t1.apply_user,
			t2.`name` apply_user_name,
			t1.apply_date,
			t1.review_user,
			t3.`name` review_user_name,
			t1.review_date,
			t1.review_remark,
			t1.storehouse_user,
			t4.`name` storehouse_user_name,
			t1.apply_storehouse_code,
			t1. STATUS,
			t1.remark,
			t1.inputuser,
			t1.crt_date,
			t1.crt_time
		FROM
			jy_apply t1
		LEFT JOIN jy_user t2 ON t1.apply_user = t2.id
		LEFT JOIN jy_user t3 ON t1.review_user = t3.id
		LEFT JOIN jy_user t4 ON t1.storehouse_user = t4.id
		WHERE
			(
				t1.apply_user = $N{sys_user_id} or
				t1.review_user = $N{sys_user_id} or
				t1.storehouse_user = $N{sys_user_id} 
			)
			AND
			(
                $ISNULL{apply_code}
                OR t1.apply_code = $S{apply_code}
            ) 
            AND
			(
                $ISNULL{id}
                OR t1.id = $N{id}
            ) 
		]]></sql>
	</sqlinfo>
	
	
	
	<sqlinfo sqlid="JY3001Q003">
		<sqlname>查询申请物资明细信息通过主表id</sqlname>
		<sql><![CDATA[
			SELECT
				t1.jy_apply_id,
				t1.jy_material_id,
				t1.apply_number,
				t2.`code` material_code,
				t2.`name` material_name,
				t2.model,
				t2.supplier,
				t3.`code` material_type_code,
				t3.`name` material_type_name
			FROM
				jy_apply_detail t1
			LEFT JOIN jy_material t2 ON t1.jy_material_id = t2.id
			LEFT JOIN jy_material_type t3 ON t2.jy_material_type_id = t3.id
			WHERE
				jy_apply_id = $N{id};
		]]></sql>
	</sqlinfo>
	
	
	<sqlinfo sqlid="JY3001D001">
		<sqlname>删除申请物资明细</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_apply_detail where jy_apply_id = $N{id}
		]]></sql>
	</sqlinfo>
	
	
	
</sqlinfos>

=== a317677438a/jywz/jywz/src/main/webapp/WEB-INF/conf/sql/MS00/MS0002/sql-MS0002-info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlinfos SYSTEM "../../../dtd/sql-info.dtd">
<sqlinfos>
	<sqlinfo sqlid="MS0002U01">
		<sqlname>新增用户信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_user 
			(loginname,passwd,role,organize_code,code,name,ophone,mphone,status) 
			VALUES 
			($S{loginname},$S{passwd},$N{role},$S{organize_code},$S{code},$S{name},
			$S{ophone},$S{mphone},$S{status})
		]]></sql>
		<checks>
			<check comparesign="gt" exitall="true">
				<checkname>新增用户信息时检查登录名称</checkname>
				<checksql>SELECT COUNT(1) FROM jy_user t WHERE t.loginname=$S{loginname}</checksql>
				<compareval>0</compareval>
				<errtext>登录名称已存在</errtext>
			</check>
		</checks>
	</sqlinfo>	
	
	<sqlinfo sqlid="MS0002U02">
		<sqlname>修改用户信息</sqlname>
		<sql><![CDATA[
			UPDATE jy_user t SET
			t.role=$N{role},
			t.organize_code=$S{organize_code},
			t.code=$S{code},
			t.name=$S{name},
			t.ophone=$S{ophone},
			t.mphone=$S{mphone}
			WHERE t.id=$N{id}
		]]></sql>
	</sqlinfo>

	<sqlinfo sqlid="MS0002U03">
		<sqlname>重置密码</sqlname>
		<sql><![CDATA[
			UPDATE jy_user  SET passwd=$S{passwd} WHERE id=$N{id}
		]]></sql>
	</sqlinfo>
	
	<sqlinfo sqlid="MS0002U04">
		<sqlname>用户状态修改</sqlname>
		<sql><![CDATA[
			UPDATE jy_user t SET t.status=$S{status} WHERE t.id=$N{id}
		]]></sql>
	</sqlinfo>	
	
	<sqlinfo sqlid="MS0002U08">
		<sqlname>删除用户信息</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_user WHERE id=$N{jy_user_id}
		]]></sql>
	</sqlinfo>	
	
	
	<sqlinfo sqlid="MS0002U09">
		<sqlname>删除用户仓库信息信息</sqlname>
		<sql><![CDATA[
			DELETE FROM jy_user_storehouse WHERE jy_user_id=$N{jy_user_id};
		]]></sql>
	</sqlinfo>	
	
	<sqlinfo sqlid="MS0002U10">
		<sqlname>新增用户仓库信息信息</sqlname>
		<sql><![CDATA[
			INSERT INTO jy_user_storehouse 
			(jy_user_id,storehouse_code) 
			VALUES 
			($N{jy_user_id},$S{storehouse_code});
		]]></sql>
	</sqlinfo>	
	
	
	<sqlinfo sqlid="MS0002Q01">
		<sqlname>用户信息列表查询</sqlname>
		<sql><![CDATA[
			SELECT t.id,t.loginname,t.passwd,t.role,t.organize_code,t.code,t.name,t.ophone,t.mphone,t.status
			FROM jy_user t  
			WHERE ($isnull{id} or t.id=$n{id}) 
			AND ($isnull{loginname} OR t.loginname LIKE  '%$U{loginname}%')
			AND ($isnull{role} OR t.id=$S{role})
			AND ($isnull{organize_code} OR t.organize_code=$S{organize_code})
			AND ($isnull{code} OR t.code LIKE  '%$U{code}%')
			AND ($isnull{name} OR t.name LIKE  '%$U{name}%')
			AND ($isnull{status} OR t.status =$S{status})
			ORDER BY t.id DESC
		]]></sql>
	</sqlinfo>	
	
	
	
	<sqlinfo sqlid="MS0002Q04">
		<sqlname>查询机构信息</sqlname>
		<sql><![CDATA[
			SELECT t.id  id, CONCAT(t.code,'-',t.name) orgname FROM jy_user t ORDER BY t.id
		]]></sql>
	</sqlinfo>	
	
	<sqlinfo sqlid="MS0002Q05">
		<sqlname>查询用户id</sqlname>
		<sql><![CDATA[
			SELECT id   FROM jy_user WHERE loginname=$S{loginname}
		]]></sql>
	</sqlinfo>	
	
	<sqlinfo sqlid="MS0002Q06">
		<sqlname>查询用户登录账号及密码</sqlname>
		<sql><![CDATA[
			SELECT  id,passwd FROM jy_user WHERE loginname=$S{loginname}
		]]></sql>
	</sqlinfo>		
	
	
	<sqlinfo sqlid="MS0002Q07">
		<sqlname>查询用户有的仓库编码</sqlname>
		<sql><![CDATA[
			SELECT storehouse_code FROM jy_user_storehouse WHERE jy_user_id=$S{sys_user_id}
		]]></sql>
	</sqlinfo>		
	
	<sqlinfo sqlid="MS0002Q08">
		<sqlname>查询其他仓库员有的仓库编码（不包括自己）</sqlname>
		<sql><![CDATA[
			SELECT storehouse_code FROM jy_user_storehouse WHERE jy_user_id!=$S{sys_user_id}
		]]></sql>
	</sqlinfo>	
			
</sqlinfos>
